apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cmk-workload7-pod
  name: cmk-workload7-pod
# Consumed by mutating webhook
  annotations:
    cmk.intel.com/mutate: "true" # accepted values to trigger mutation: "true", "True", "1"
  namespace: cmk-namespace
spec:
  selector:
   matchLabels:
    app: cmk-workload7-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: cmk-workload7-pod
    spec:
     serviceAccountName: cmk-serviceaccount
     tolerations:
     - operator: "Exists"
     containers:
      - name: cmk-isolate-shared-workload7
        image: hrabhijith2/play:sample1
        imagePullPolicy: Always
        ports:
         - containerPort: 5005
           hostPort: 5005
        env:
        - name: CMK_PROC_FS
          value: "/host/proc"
        volumeMounts:
         - name: tmp
           mountPath: "/tmp"
         - mountPath: "/host/proc"
           name: cmk-host-proc
           readOnly: true
         - mountPath: "/opt/bin"
           name: cmk-install-dir
         - mountPath: "/etc/cmk"
           name: cmk-conf-dir
        securityContext:
         allowPrivilegeEscalation: true
         readOnlyRootFilesystem: true
         runAsNonRoot: false
         privileged: true
         capabilities:
          drop:
           - all
     volumes:
      - hostPath:
         path: "/tmp"
        name: tmp
      - hostPath:
      # Change this to modify the CMK installation dir in the host file system.
         path: "/opt/bin"
        name: cmk-install-dir
      - hostPath:
         path: "/proc"
        name: cmk-host-proc
      - hostPath:
       # Change this to modify the CMK config dir in the host file system.
         path: "/etc/cmk"
        name: cmk-conf-dir
     nodeSelector:
      kubernetes.io/hostname: "alderlake"
      
