apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cmk-workload1-pod
  name: cmk-workload1-pod
# Consumed by mutating webhook
  annotations:
    cmk.intel.com/mutate: "true" # accepted values to trigger mutation: "true", "True", "1"
  namespace: cmk-namespace
spec:
  selector:
   matchLabels:
    app: cmk-workload1-pod
  replicas: 0
  template:
    metadata:
      labels:
        app: cmk-workload1-pod
    spec:
      serviceAccountName: cmk-serviceaccount
      tolerations:
      - operator: "Exists"
      containers:
      - name: cmk-isolate-exclusive-workload
        image: hrabhijith2/rpi-detection:motionx86
        imagePullPolicy: Always
        tty: true
        ports:
         - containerPort: 5006
           hostPort: 5006
        env:
        - name: CMK_PROC_FS
          value: "/host/proc"
        resources:
         requests:
          cmk.intel.com/exclusive-cores: '1'
         limits:
          cmk.intel.com/exclusive-cores: '1'
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
        - name: dev-video0
          mountPath: "/dev/video0"
        - name: tmp
          mountPath: "/tmp"
        - mountPath: "/host/proc"
          name: cmk-host-proc
          readOnly: true
        - mountPath: "/opt/bin"
          name: cmk-install-dir
        - mountPath: "/etc/cmk"
          name: cmk-conf-dir
        securityContext:
         allowPrivilegeEscalation: true
         readOnlyRootFilesystem: true
         runAsNonRoot: false
         privileged: true
         capabilities:
          drop:
           - all
      volumes:
      - hostPath:
         path: "/tmp"
        name: tmp
      - name: dev-video0
        hostPath:
         path: "/dev/vid
      - hostPath:
         path: "/opt/bin"
        name: cmk-install-dir
      - hostPath:
         path: "/proc"
        name: cmk-host-proc
      - hostPath:
         path: "/etc/cmk"
        name: cmk-conf-direo0"
      nodeSelector:
       kubernetes.io/hostname: "katpk029"
