apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cmk-workload2-pod
  name: cmk-workload2-pod
# Consumed by mutating webhook
  annotations:
    cmk.intel.com/mutate: "true" # accepted values to trigger mutation: "true", "True", "1"
  namespace: cmk-namespace
spec:
  selector:
   matchLabels:
    app: cmk-workload2-pod
  replicas: 0
  template:
    metadata:
      labels:
        app: cmk-workload2-pod
    spec:
     serviceAccountName: cmk-serviceaccount
     containers:
      - name: cmk-isolate-exclusive-workload2
        image: hrabhijith2/face-detection:x86
        ports:
         - containerPort: 5000
           hostPort: 5000
        env:
        - name: CMK_NUM_CORES
          value: "1"
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          cmk.intel.com/exclusive-cores: '1'
         limits:
          cmk.intel.com/exclusive-cores: '1'
        volumeMounts:
         - name: tmp
           mountPath: "/tmp"
        securityContext:
         allowPrivilegeEscalation: true
         readOnlyRootFilesystem: true
         runAsNonRoot: false
         privileged: true
         capabilities:
          drop:
           - all
     volumes:
      - hostPath:
         path: "/tmp"
        name: tmp
